/*
 * Legislate API
 * The Legislate API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.legislate.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.legislate.model.IdentityFieldsCollaboratorRoleRequestDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * UpdateCollaboratorIdentityFieldsRequestDTO
 */


public class UpdateCollaboratorIdentityFieldsRequestDTO {
  @SerializedName("fields")
  private List<IdentityFieldsCollaboratorRoleRequestDTO> fields = new ArrayList<IdentityFieldsCollaboratorRoleRequestDTO>();

  public UpdateCollaboratorIdentityFieldsRequestDTO fields(List<IdentityFieldsCollaboratorRoleRequestDTO> fields) {
    this.fields = fields;
    return this;
  }

  public UpdateCollaboratorIdentityFieldsRequestDTO addFieldsItem(IdentityFieldsCollaboratorRoleRequestDTO fieldsItem) {
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * The collaborator fields you&#x27;d like to update with new values.
   * @return fields
  **/
  @Schema(required = true, description = "The collaborator fields you'd like to update with new values.")
  public List<IdentityFieldsCollaboratorRoleRequestDTO> getFields() {
    return fields;
  }

  public void setFields(List<IdentityFieldsCollaboratorRoleRequestDTO> fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCollaboratorIdentityFieldsRequestDTO updateCollaboratorIdentityFieldsRequestDTO = (UpdateCollaboratorIdentityFieldsRequestDTO) o;
    return Objects.equals(this.fields, updateCollaboratorIdentityFieldsRequestDTO.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCollaboratorIdentityFieldsRequestDTO {\n");
    
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
