/*
 * Legislate API
 * The Legislate API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CompanyCreatedResponseDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-07T16:18:08.349882+02:00[Europe/Madrid]")
public class CompanyCreatedResponseDTO {
  @SerializedName("company_name")
  private String companyName = null;

  @SerializedName("contract_collaborator_id")
  private Long contractCollaboratorId = null;

  @SerializedName("contract_id")
  private Long contractId = null;

  public CompanyCreatedResponseDTO companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @Schema(description = "")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public CompanyCreatedResponseDTO contractCollaboratorId(Long contractCollaboratorId) {
    this.contractCollaboratorId = contractCollaboratorId;
    return this;
  }

   /**
   * Get contractCollaboratorId
   * @return contractCollaboratorId
  **/
  @Schema(description = "")
  public Long getContractCollaboratorId() {
    return contractCollaboratorId;
  }

  public void setContractCollaboratorId(Long contractCollaboratorId) {
    this.contractCollaboratorId = contractCollaboratorId;
  }

  public CompanyCreatedResponseDTO contractId(Long contractId) {
    this.contractId = contractId;
    return this;
  }

   /**
   * Get contractId
   * @return contractId
  **/
  @Schema(description = "")
  public Long getContractId() {
    return contractId;
  }

  public void setContractId(Long contractId) {
    this.contractId = contractId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyCreatedResponseDTO companyCreatedResponseDTO = (CompanyCreatedResponseDTO) o;
    return Objects.equals(this.companyName, companyCreatedResponseDTO.companyName) &&
        Objects.equals(this.contractCollaboratorId, companyCreatedResponseDTO.contractCollaboratorId) &&
        Objects.equals(this.contractId, companyCreatedResponseDTO.contractId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, contractCollaboratorId, contractId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyCreatedResponseDTO {\n");
    
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    contractCollaboratorId: ").append(toIndentedString(contractCollaboratorId)).append("\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
