/*
 * Legislate API
 * The Legislate API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IdentityFieldsCollaboratorRoleRequestDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-07T16:18:08.349882+02:00[Europe/Madrid]")
public class IdentityFieldsCollaboratorRoleRequestDTO {
  @SerializedName("id")
  private String id = null;

  @SerializedName("value")
  private String value = null;

  public IdentityFieldsCollaboratorRoleRequestDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the field you&#x27;d like to update.
   * @return id
  **/
  @Schema(required = true, description = "The id of the field you'd like to update.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public IdentityFieldsCollaboratorRoleRequestDTO value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The new value of the contract field.
   * @return value
  **/
  @Schema(required = true, description = "The new value of the contract field.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentityFieldsCollaboratorRoleRequestDTO identityFieldsCollaboratorRoleRequestDTO = (IdentityFieldsCollaboratorRoleRequestDTO) o;
    return Objects.equals(this.id, identityFieldsCollaboratorRoleRequestDTO.id) &&
        Objects.equals(this.value, identityFieldsCollaboratorRoleRequestDTO.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentityFieldsCollaboratorRoleRequestDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
