/*
 * Legislate API
 * The Legislate API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.IdentityFieldOptionDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * IdentityFieldsCollaboratorRoleDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-07T16:18:08.349882+02:00[Europe/Madrid]")
public class IdentityFieldsCollaboratorRoleDTO {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("options")
  private List<IdentityFieldOptionDTO> options = null;

  @SerializedName("validationType")
  private String validationType = null;

  @SerializedName("value")
  private String value = null;

  public IdentityFieldsCollaboratorRoleDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The unique Id of the field you&#x27;d like to update.
   * @return id
  **/
  @Schema(required = true, description = "The unique Id of the field you'd like to update.")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public IdentityFieldsCollaboratorRoleDTO label(String label) {
    this.label = label;
    return this;
  }

   /**
   * The label of the field you&#x27;d like to update.
   * @return label
  **/
  @Schema(description = "The label of the field you'd like to update.")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public IdentityFieldsCollaboratorRoleDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the field you&#x27;d like to update.
   * @return name
  **/
  @Schema(description = "The name of the field you'd like to update.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IdentityFieldsCollaboratorRoleDTO options(List<IdentityFieldOptionDTO> options) {
    this.options = options;
    return this;
  }

  public IdentityFieldsCollaboratorRoleDTO addOptionsItem(IdentityFieldOptionDTO optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<IdentityFieldOptionDTO>();
    }
    this.options.add(optionsItem);
    return this;
  }

   /**
   * The options of the field you&#x27;d like to update if applicable.
   * @return options
  **/
  @Schema(description = "The options of the field you'd like to update if applicable.")
  public List<IdentityFieldOptionDTO> getOptions() {
    return options;
  }

  public void setOptions(List<IdentityFieldOptionDTO> options) {
    this.options = options;
  }

  public IdentityFieldsCollaboratorRoleDTO validationType(String validationType) {
    this.validationType = validationType;
    return this;
  }

   /**
   * Get validationType
   * @return validationType
  **/
  @Schema(description = "")
  public String getValidationType() {
    return validationType;
  }

  public void setValidationType(String validationType) {
    this.validationType = validationType;
  }

  public IdentityFieldsCollaboratorRoleDTO value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The new value of the contract field.
   * @return value
  **/
  @Schema(required = true, description = "The new value of the contract field.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentityFieldsCollaboratorRoleDTO identityFieldsCollaboratorRoleDTO = (IdentityFieldsCollaboratorRoleDTO) o;
    return Objects.equals(this.id, identityFieldsCollaboratorRoleDTO.id) &&
        Objects.equals(this.label, identityFieldsCollaboratorRoleDTO.label) &&
        Objects.equals(this.name, identityFieldsCollaboratorRoleDTO.name) &&
        Objects.equals(this.options, identityFieldsCollaboratorRoleDTO.options) &&
        Objects.equals(this.validationType, identityFieldsCollaboratorRoleDTO.validationType) &&
        Objects.equals(this.value, identityFieldsCollaboratorRoleDTO.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, name, options, validationType, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentityFieldsCollaboratorRoleDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    validationType: ").append(toIndentedString(validationType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
