/*
 * Legislate API
 * The Legislate API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ContractResponseDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ContractTypeTemplateApi
 */
@Ignore
public class ContractTypeTemplateApiTest {

    private final ContractTypeTemplateApi api = new ContractTypeTemplateApi();

    /**
     * Get contract template.
     *
     * This operation will retrieve details about a given contract.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTemplateUsingGETTest() throws Exception {
        Long contractTypeId = null;
        Long teamId = null;
        Long templateId = null;
        ContractResponseDTO response = api.getTemplateUsingGET(contractTypeId, teamId, templateId);

        // TODO: test validations
    }
    /**
     * Get the latest template version for a contract type
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTemplatesUsingGETTest() throws Exception {
        Long contractTypeId = null;
        Long teamId = null;
        ContractResponseDTO response = api.getTemplatesUsingGET(contractTypeId, teamId);

        // TODO: test validations
    }
}
